### ISSUE TITLE
Query Token Input Format

### ISSUE THREAD

**Issue by codingnoobneedshelp** [airalcorn2/LMIR#1]
Hello, 

what should the format of the Parameter query_tokens be?

The code is not working for me :(

I have initialized the LMIR model with list of lists of tokens. And as Query have a tokenized list.

I get this error:

  File "C:/Users/XXX/lmir.py", line 65, in jelinek_mercer
    score -= log((1 - lamb) * p_ml[token] + lamb * p_C[token])

KeyError: 'hey'

Maybe you can help me?

Regards

**Comment by airalcorn2** [comment]
Is "hey" in your corpus? This was a minimal implementation, so I didn't add proper checks. All of the dictionary queries should be `.get`s for real world applications. E.g.:

`p_ml[token]` would be `p_ml.get(token, 0)`.

**Comment by codingnoobneedshelp** [comment]
Hey, no hey is just one Token in my corpus. Have you maybe a working Code for this? p_ml.get(token, 0) This does not working, because p_ml is a List of Dicts.Thanks and regardsSergej---- On Mo, 25 Jun 2018 15:10:58 +0200  Michael A. Alcorn<notifications@github.com> wrote ----Is "hey" in your corpus? This was a minimal implementation, so I didn't add proper checks. All of the dictionary queries should be .gets for real world applications. E.g.: p_ml[token] would be p_ml.get(token, 0).  —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by airalcorn2** [comment]
[`p_ml` is a dictionary.](https://github.com/airalcorn2/LMIR/blob/master/lmir.py#L64) I updated the code with the necessary `.get`s and added a README with an example. Let me know if that doesn't fix everything for you.

**Comment by codingnoobneedshelp** [comment]
Hey mate,  thanks for your help and the quick response. Unfortunately, i can't still run the query. Even with the example you posted on github it is not working: import lmir doc_1 = "This is document one.".split() doc_2 = "This is document two. It contains different words.".split() docs = [doc_1, doc_2] models = lmir.LMIR(docs) print(models.jelinek_mercer("This document has some words that match.".split())) Traceback (most recent call last):   File "<ipython-input-4-c3cfd01b525d>", line 1, in <module>     print(models.jelinek_mercer("This document has some words that match.".split()))   File "C:\Users\XXX\lmir.py", line 65, in jelinek_mercer     score -= log((1 - lamb) * p_ml.get(token, 0) + lamb * p_C.get(token, 0)) ValueError: math domain error Any chance you can look into the problem? Thanks and Regards ---- On Mo, 25 Jun 2018 17:34:44 +0200 Michael A. Alcorn <notifications@github.com> wrote ---- p_ml is a dictionary. I updated the code with the necessary .gets and added a README with an example. Let me know if that doesn't fix everything for you. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by airalcorn2** [comment]
You have to use Python 3.

**Comment by codingnoobneedshelp** [comment]
I'm using python 3.6

**Comment by codingnoobneedshelp** [comment]
Its working. thanks for your help
